### ISSUE TITLE
syncdb fails with DatabaseError: (1170, "BLOB/TEXT column 'group' used in key specification without a key length")

### ISSUE THREAD

**Issue by flesser** [charettes/django-mutant#17]
I was following the instructions from http://integricho.github.io/2013/07/22/mutant-introduction/ in order to get started with my own django-mutant experiments.
When trying to sync the db, i get the following error:

```
$ python manage.py syncdb
Syncing...
Creating tables ...
Creating table mutant_modeldefinition
Creating table mutant_basedefinition
Creating table mutant_orderingfielddefinition
Creating table mutant_uniquetogetherdefinition_field_defs
Creating table mutant_uniquetogetherdefinition
Creating table mutant_fielddefinition
Creating table mutant_fielddefinitionchoice
DatabaseError: (1170, "BLOB/TEXT column 'group' used in key specification without a key length")
```

What am I doing wrong?
/edit: I'm using MySQL as backend.

**Comment by afshinm** [comment]
I had the same problem and fixed that after changing database engine from Mysql to Postgres.

**Comment by charettes** [comment]
It's expected as this project **doesn't** support MySQL and will never do unless it adds support for transactional DDL.

**Comment by afshinm** [comment]
Sure, I wish it was mentioned somewhere though.
