### ISSUE TITLE
Django 1.7 support

### ISSUE THREAD

**Issue by shlomiassaf** [charettes/django-mutant#25]
Hi,

In root README.MD you state that you are planning to drop the South dependency, this will actually drop support for django 1.6 and below.

Since this is an open source project, would you consider supporting both?

Here is a nice read about combining south & django 1.7 native "migrations"
http://treyhunner.com/2014/03/migrating-to-django-1-dot-7/

While it is quite simple to implement for most project it will not be a cake for this project as it makes extensive use of South.

But I`m sure it can be set.

Thanks.

**Comment by dmr** [comment]
What is the status of this project? Are you still using it, or is there another project that replaced the project for you?

**Comment by charettes** [comment]
I'm still using it, but I haven't find the time to port it to 1.7 yet.

**Comment by charettes** [comment]
Since 1.6 end-of-life is approaching I'll need to port it in the next months.

**Comment by dmr** [comment]
Thanks for the quick reply, I'm relying on django 1.7 so I'll keep using my own solution for the dynamic properties problem for now

**Comment by COLABORATI** [comment]
@dmr may I ask what kind of solution you are using? I am too interested in the problem of django dynamic models. Thanks!

**Comment by dmr** [comment]
@COLABORATI Currently we are using our own implementation, a combination of a jsonfield and a custom jsonschema-like language with validictory for validation and mostly elasticsearch for lookups. If I'd start from scratch I would probably give django-hstore a try.

**Comment by COLABORATI** [comment]
ah, ok, thanks, I was also looking at django-hstore. Have a nice day!

**Comment by charettes** [comment]
See #33.
