### ISSUE TITLE
Dependecies for pip not working

### ISSUE THREAD

**Issue by PerFuchs** [charettes/django-mutant#31]
Dear charettes,

your dependency to django-orderable is not working. You are not using the django-orderable package witch is on pip-index. So in your requirements described  with "django-orderable", it will take the wrong one.
This happens since dependency_links for pip are deprecated (http://serverfault.com/questions/608192/pip-install-seems-to-be-ignoring-dependency-links).

I guess, a good solution would be to put the link to django-orderable on git directly in your requirements.

Thanks for developing on this project :)

Regards
Per Fuchs

**Comment by charettes** [comment]
Hi @PerFuchs thanks for your report!

The latest version of django-mutant dropped it's dependency on django-orderable so it shouldn't be an issue anymore.

Is it possible for your to upgrade to version 0.1.2?

**Comment by PerFuchs** [comment]
Yes, hope this will be possible. This is one of my next tasks anyhow. Thanks for the fast answer.
