### ISSUE TITLE
ImportError: cannot import name 'force_unicode'

### ISSUE THREAD

**Issue by snavien** [charettes/django-mutant#35]
ImportError: cannot import name 'force_unicode'

installed in my virtualenv:
bbcode==1.0.21
Django==1.8.3
django-annoying==0.8.3
django-mutant==0.1.2
django-picklefield==0.3.1
django-polymodels==1.3.1
django-registration-redux==1.2
Pillow==2.9.0
psycopg2==2.6.1
six==1.9.0
sorl-thumbnail==12.3
South==1.0.2
Unidecode==0.4.18
wheel==0.24.0

and using Python3.4.3 

I just put it in the installed apps and ran pip install django-mutant; However I'm not sue if there are supposed to be other requirements?

**Comment by charettes** [comment]
Mutant doesn't support Django 1.8 yet. Please refer to #33.
