### ISSUE TITLE
Error when creating ManyToMany Field with Django 1.9.5.

### ISSUE THREAD

**Issue by ivicaljubicic** [charettes/django-mutant#45]
Hi,
I'm using Django-Mutant in my project and when trying to create a ManyToMany Field the following Error occurs:

File "C:\Python34\lib\site-packages\django\db\backends\base\schema.py", line 3
81, in add_field
    if field.many_to_many and field.remote_field.through._meta.auto_created:
AttributeError: 'NoneType' object has no attribute '_meta'

The error indicates that field.remote_field.through attribute does not exist which it does not.

I'm using the following code to create a ManyToMany Field

 fieldl,created= ManyToManyFieldDefinition.objects.update_or_create(model_def=model, name=field.FieldName+str(field.id), to=related_ct, null=True, blank=True)

When I debug the data it looks ok:
(Pdb) args
self = <ManyToManyFieldDefinition: ManyToManyFieldDefinition object>
args = ()
kwargs = {'to': <ContentType: task def>, 'blank': True, 'name': 'Field290', 'mod
el_def': <ModelDefinition: resources.resource5>, 'null': True}

Am i missing something or mutant and Django 1.9.5 just don't play well.

Thanks,
Ivica

**Comment by charettes** [comment]
See #2, `ManyToManyFieldDefinition` is known to be buggy.
