### ISSUE TITLE
error in makemigrations

### ISSUE THREAD

**Issue by caoguangyao** [charettes/django-mutant#46]
Hi charettes,

when i use 

> python manage.py makemigrations

it get an error about

> TypeError: Couldn't reconstruct field content_type on mutant.FieldDefinition: __init__() got multiple values for keyword argument 'polymorphic_type'

How do I deal with it?

**Comment by charettes** [comment]
Try upgrading to the latest `django-polymodels` and `django-mutant` alpha version, this should be fixed.

**Comment by NoraGithub** [comment]
which one is the alpha version? @charettes

**Comment by NoraGithub** [comment]
im on the master, i dont see any branch or tags name alpha.

**Comment by NoraGithub** [comment]
thanks
