### ISSUE TITLE
FieldDefinition didn't define any `field_class`.

### ISSUE THREAD

**Issue by caoguangyao** [charettes/django-mutant#47]
Hi charettes,
it seems models.FieldDefinition can register in django admin page,
but when i filled the form and click the save button
it gives the error page, and say FieldDefinition didn't define any `field_class`.

> NotImplementedError at /admin/mutant/fielddefinition/add/
> FieldDefinition didn't define any `field_class`.
> Request Method: POST
> Request URL:    http://localhost:8000/admin/mutant/fielddefinition/add/

so how to define a customized field , 
I think it is useful for new bee to understand about dynamic model

otherwise ,I want to store my customized fields in a table ,what should I do?

**Comment by charettes** [comment]
You can't simply use the admin with model and field definition. In this case you'll have to make sure to create a `FieldDefinition` subclass through a specialized form class.

**Comment by twz915** [comment]
Could you give me an example? @charettes

**Comment by antoniocdff** [comment]
I need a example too =/

**Comment by claudels** [comment]
Has anyone solved this issue?
