### ISSUE TITLE
TypeError: Couldn't reconstruct field content_type on mutant.FieldDefinition: __init__() got multiple values for keyword argument 'polymorphic_type'

### ISSUE THREAD

**Issue by caoguangyao** [charettes/django-mutant#49]
I add a static model and do some change in my models.py

After I run

> python manage.py migrate --fake-initial

the command 

> python manage.py makemigrations 

does not work ,and  throws the exception:

> TypeError: Couldn't reconstruct field content_type on mutant.FieldDefinition: **init**() got multiple values for keyword argument 'polymorphic_type'

how do I re-sync my database?

**Comment by afshinm** [comment]
I think the problem is using Mysql. I had the same problem and fixed the after changing it to Postgres.

**Comment by charettes** [comment]
Thanks for the report @afshinm.

**Comment by RAZZ121** [comment]
I am using postgres but it show the same error .
