### ISSUE TITLE
Django-mutant migration issues ( with fix )

### ISSUE THREAD

**Issue by artemistomaras** [charettes/django-mutant#51]
If there is a model defined that has a relation to the mutant ModelDefinition model, the whole migration chain breaks up.

The reason that this happens is that the "contenttypes  0002_remove_content_type_name" migration needs to run before the mutant initial migration. Because of this, things like running tests ( that require a database to be made )
 or migrating from scratch will not work.

A possible fix is to modify the 0001_initial.py mutant migration file and change the depedencies to `    dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
    ]`

Here is the mentioned [error](https://github.com/charettes/django-mutant/files/580633/error.txt)

**Comment by charettes** [comment]
We cannot the change the dependencies of a migration. The issue here is related to [Django #24182](https://code.djangoproject.com/ticket/24182) and will be tracked in charettes/django-polymodels#38.
